/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    MyFileReader meRead = new MyFileReader();
    meRead.FindNoSemiColon();
    }
}
