/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.ArrayList;
import java.util.Random;
import java.util.List;
import java.text.DecimalFormat;
public class Library {
    //Feature 1: roll the Dice and return the values of each time
    public int[] roll(int n) {
        int[] rollResult = new int[n];
        for(int i=0;i<rollResult.length;i++){
            rollResult[i] = new Random().nextInt(6)+1;
        }
       return rollResult;
    }

    //Feature 2: check if the array contains duplicate values
    public boolean containsDuplicates(int[] inputArr) {
        List<Integer> list = new ArrayList<Integer>();
        for(int n : inputArr){
            if(!list.contains(n)){
                list.add(n);
            }
            //found duplicates return true means it has duplicates
            else return true;
        }
        //if does not have duplicates, return false
    return false ;
    }

   //Feature 3: calculate averages in the array
   public String calAvg(int[] inputArr){
       double sum = 0.0;
       for(int n : inputArr ){
           sum += n;
       }
       DecimalFormat df = new DecimalFormat("#.##");
       return df.format(sum/inputArr.length);
   }

   //Feature 4: calculat average value for each array and return the lowest average array
    public int[] calLowestAvg(int[][] inputArrs){
        double[] avg = new double[inputArrs.length];
        for(int i=0;i<inputArrs.length;i++){
             int sum = 0;
            for(int j=0;j<inputArrs[i].length;j++){

                sum +=inputArrs[i][j];
            }
           avg[i] = sum/inputArrs[i].length;
        }
        double preLow = avg[0];
        int idx = 0;
        for(int k=1;k<avg.length;k++){
            if(avg[k]<preLow){
                preLow = avg[k];
                idx = k;
            }
        }
        return inputArrs[idx];
    }
}
